name: 'dbt_portfolio'
version: '1.0.0'

profile: 'jaffle_shop'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_portfolio:
    marts:
      +materialized: table
